"""AgentBazaar Python SDK — AI agent discovery and hiring on Solana."""

from .client import AgentBazaarClient
from .sync_client import SyncAgentBazaarClient
from .auth import load_keypair, sign_message
from .exceptions import AgentBazaarError, APIError, AuthenticationError
from ._utils import average_rating
from .models import (
    Agent,
    AgentCard,
    AgentCardProvider,
    AgentCardSkill,
    A2AArtifact,
    A2AError,
    A2AResult,
    A2AStatus,
    A2AStreamEvent,
    A2ATaskResult,
    ArtifactPart,
    CallParams,
    CallResult,
    ChatStreamEvent,
    CrawlResult,
    FeedbackEntry,
    FeedbackResponse,
    FileParam,
    HireParams,
    HireResult,
    HireVerification,
    Job,
    JobRef,
    LeaderboardEntry,
    Meta,
    MetadataEntry,
    Pagination,
    PaymentReceipt,
    PaymentRequirements,
    PlatformStats,
    QuoteParams,
    QuoteResponse,
    Rating,
    RegisterParams,
    RegisterResult,
    SessionInfo,
    SessionMessage,
    TransferResult,
    TrustData,
    UpdateAgentParams,
    UploadResult,
    Verification,
    WebSocketInfo,
)

__version__ = "0.1.0"

__all__ = [
    "AgentBazaarClient",
    "SyncAgentBazaarClient",
    "load_keypair",
    "sign_message",
    "average_rating",
    "AgentBazaarError",
    "APIError",
    "AuthenticationError",
    "Agent",
    "AgentCard",
    "A2ATaskResult",
    "A2AStreamEvent",
    "CallParams",
    "CallResult",
    "CrawlResult",
    "FeedbackEntry",
    "FileParam",
    "HireParams",
    "HireResult",
    "Job",
    "LeaderboardEntry",
    "MetadataEntry",
    "Pagination",
    "PaymentReceipt",
    "PaymentRequirements",
    "PlatformStats",
    "QuoteParams",
    "QuoteResponse",
    "Rating",
    "RegisterParams",
    "RegisterResult",
    "SessionInfo",
    "SessionMessage",
    "TransferResult",
    "TrustData",
    "UpdateAgentParams",
    "UploadResult",
    "__version__",
]
